/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAiToolsRouteImport } from './routes/app/ai-tools'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAssignmentsRouteImport } from './routes/app/assignments'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppGradebookRouteImport } from './routes/app/gradebook'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppPricingRouteImport } from './routes/app/pricing'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppExamsIndexRouteImport } from './routes/app/exams.index'
import { Route as AppExamsExamIdRouteImport } from './routes/app/exams.$examId'
import { Route as AppStudentsIndexRouteImport } from './routes/app/students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiToolsRoute = AppAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsIndexRoute = AppExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsExamIdRoute = AppExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams/': typeof AppExamsIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams': typeof AppExamsIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams/': typeof AppExamsIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams/'
    | '/app/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams'
    | '/app/students'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams/'
    | '/app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-tools': {
      id: '/app/ai-tools'
      path: '/ai-tools'
      fullPath: '/app/ai-tools'
      preLoaderRoute: typeof AppAiToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gradebook': {
      id: '/app/gradebook'
      path: '/gradebook'
      fullPath: '/app/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams/': {
      id: '/app/exams/'
      path: '/exams'
      fullPath: '/app/exams/'
      preLoaderRoute: typeof AppExamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams/$examId': {
      id: '/app/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/app/exams/$examId'
      preLoaderRoute: typeof AppExamsExamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiToolsRoute: typeof AppAiToolsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppHelpRoute: typeof AppHelpRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExamsExamIdRoute: typeof AppExamsExamIdRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppExamsIndexRoute: typeof AppExamsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiToolsRoute: AppAiToolsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppHelpRoute: AppHelpRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExamsExamIdRoute: AppExamsExamIdRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppExamsIndexRoute: AppExamsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
