/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAiToolsRouteImport } from './routes/app/ai-tools'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAssignmentsRouteImport } from './routes/app/assignments'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppGradebookRouteImport } from './routes/app/gradebook'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppPricingRouteImport } from './routes/app/pricing'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppExamsIndexRouteImport } from './routes/app/exams.index'
import { Route as AppExamsExamIdRouteImport } from './routes/app/exams.$examId'
import { Route as AppStudentsIndexRouteImport } from './routes/app/students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app/students.$studentId'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiToolsRoute = AppAiToolsRouteImport.update({
  id: '/app/ai-tools',
  path: '/app/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/app/assignments',
  path: '/app/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/app/gradebook',
  path: '/app/gradebook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/app/help',
  path: '/app/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/app/pricing',
  path: '/app/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExamsIndexRoute = AppExamsIndexRouteImport.update({
  id: '/app/exams/',
  path: '/app/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExamsExamIdRoute = AppExamsExamIdRouteImport.update({
  id: '/app/exams/$examId',
  path: '/app/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/app/students/',
  path: '/app/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/app/students/$studentId',
  path: '/app/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams/': typeof AppExamsIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams': typeof AppExamsIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/ai-tools': typeof AppAiToolsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/gradebook': typeof AppGradebookRoute
  '/app/help': typeof AppHelpRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/exams/$examId': typeof AppExamsExamIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/exams/': typeof AppExamsIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams/'
    | '/app/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams'
    | '/app/students'
  id:
    | '__root__'
    | '/app/ai-tools'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/gradebook'
    | '/app/help'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/app/exams/$examId'
    | '/app/students/$studentId'
    | '/app/exams/'
    | '/app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppAiToolsRoute: typeof AppAiToolsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppHelpRoute: typeof AppHelpRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExamsExamIdRoute: typeof AppExamsExamIdRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppExamsIndexRoute: typeof AppExamsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ai-tools': {
      id: '/app/ai-tools'
      path: '/app/ai-tools'
      fullPath: '/app/ai-tools'
      preLoaderRoute: typeof AppAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/app/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gradebook': {
      id: '/app/gradebook'
      path: '/app/gradebook'
      fullPath: '/app/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/help': {
      id: '/app/help'
      path: '/app/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/app/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/exams/': {
      id: '/app/exams/'
      path: '/app/exams'
      fullPath: '/app/exams/'
      preLoaderRoute: typeof AppExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/exams/$examId': {
      id: '/app/exams/$examId'
      path: '/app/exams/$examId'
      fullPath: '/app/exams/$examId'
      preLoaderRoute: typeof AppExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/app/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/app/students/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppAiToolsRoute: AppAiToolsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppHelpRoute: AppHelpRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExamsExamIdRoute: AppExamsExamIdRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppExamsIndexRoute: AppExamsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
